import localFont from "next/font/local";

export const doldam = localFont({
  src: [
    {
      path: "../assets/fonts/doldam.woff",
    },
    {
      path: "../assets/fonts/doldam.woff2",
    },
  ],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
