export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="bg-blue-100 p-4">
        <div className="bg-yellow-200 p-2 border-2 border-yellow-600">
          🔵 루트 레이아웃 (항상 존재!)
          {children}
        </div>
      </body>
    </html>
  );
}
